name: facemask
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1=py37_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.3=he6710b0_1
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1g=h7b6447c_0
  - pip=20.0.2=py37_3
  - python=3.7.7=hcff3b4d_5
  - readline=8.0=h7b6447c_0
  - setuptools=46.4.0=py37_0
  - sqlite=3.31.1=h62c20be_1
  - tk=8.6.8=hbc83047_0
  - wheel=0.34.2=py37_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.9.0
    - astor==0.8.1
    - cachetools==4.1.0
    - chardet==3.0.4
    - cycler==0.10.0
    - gast==0.2.2
    - google-auth==1.14.1
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - grpcio==1.28.1
    - h5py==2.10.0
    - idna==2.9
    - imutils==0.5.3
    - joblib==0.14.1
    - keras==2.3.1
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - kiwisolver==1.2.0
    - markdown==3.2.1
    - matplotlib==3.2.1
    - numpy==1.18.4
    - oauthlib==3.1.0
    - opencv-python==4.2.0.34
    - opt-einsum==3.2.1
    - pillow==7.1.2
    - protobuf==3.11.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygame==1.9.6
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pyyaml==5.3.1
    - requests==2.23.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - scikit-learn==0.22.2.post1
    - scipy==1.4.1
    - six==1.14.0
    - tensorboard==2.0.1
    - tensorflow-estimator==2.0.1
    - tensorflow-gpu==2.0.1
    - tensorflow-hub==0.8.0
    - termcolor==1.1.0
    - urllib3==1.25.9
    - werkzeug==1.0.1
    - wincertstore==0.2
    - wrapt==1.12.1
prefix: /home/ideaslocascdo/anaconda3/envs/facemask

